--CHECKS IF EXISTS THE ADMIN LOGIN IN THE DATABASE, IF IT DOES, REPLACES IT WITH THE PASSWORD VALUE FROM THE KEYVAULT
--IF DOESN'T EXISTS, CREATES IT

IF EXISTS
    (SELECT name FROM master.sys.sql_logins WHERE name = '#{adminLogin-DB}#')
BEGIN
    ALTER LOGIN "#{adminLogin-DB}#" WITH PASSWORD='#{adminLoginPWD-DB}#';
END
ELSE
BEGIN
    CREATE LOGIN "#{adminLogin-DB}#" WITH PASSWORD='#{adminLoginPWD-DB}#';
END


--CHECKS IF EXISTS THE READ LOGIN IN THE DATABASE, IF EXISTS, REPLACES IT WITH THE PASSWORD VALUE FROM THE KEYVAULT
--IF DOESN'T EXISTS, CREATES IT

IF EXISTS
    (SELECT name FROM master.sys.sql_logins WHERE name = '#{readLogin-DB}#')
BEGIN
    ALTER LOGIN "#{readLogin-DB}#" WITH PASSWORD='#{readLoginPWD-DB}#';
END
ELSE
BEGIN
    CREATE LOGIN "#{readLogin-DB}#" WITH PASSWORD='#{readLoginPWD-DB}#';
END