jobs:
- job: ElasticAgent_Deploy_Job
  pool:
    pool:
    name: $(agent-pool-name)
    demands:
    - agent.os -equals Linux

  steps:
  #publish secrets to the keyvault
  - task: AzureCLI@2
    displayName: Publish Secrets to Keyvault
    inputs:
      azureSubscription: '$(azure-subscription)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      failOnStandardError: true
      inlineScript: |
        SECRETS_LIST="
        fleet-url|==|$(FLEET_URL)
        fleet-enrollment-token|==|$(FLEET_ENROLLMENT_TOKEN)
        "
        for s in $SECRETS_LIST ; do
          secret_name=${s%|==|*}
          secret_value=${s#*|==|}
          az keyvault secret set --name $secret_name --value $secret_value --vault-name '$(shared-keyvault)' --output none
          echo $secret_name" published" 
        done

 # replacement of variables in the scripts to create DB logins and RabbitMQ resources
  - task: replacetokens@5
    displayName: Values Replacements in script files
    inputs:
      rootDirectory: '$(System.DefaultWorkingDirectory)/deployment/pipelines-files/kubernetes-files/elastic-agent'
      targetFiles: |
        elastic-agent-daemonset.yaml
        elastic-agent-win-daemonset.yaml
      encoding: 'auto'
      writeBOM: true
      actionOnMissing: 'fail'
      keepToken: false
      tokenPrefix: '#{'
      tokenSuffix: '}#'

  #create elasti-agent containers inside the cluster
  - task: Kubernetes@1
    displayName: Deploy Linux Elastic Agent daemonset in Kubernetes
    inputs:
      connectionType: 'None'
      forceUpdate: true
      command: apply
      arguments: -f $(System.DefaultWorkingDirectory)/deployment/pipelines-files/kubernetes-files/elastic-agent/elastic-agent-daemonset.yaml
      secretType: 'generic'

  #create elasti-agent windows containers inside the cluster
  - task: Kubernetes@1
    displayName: Deploy Windows Elastic Agent in Kubernetes
    inputs:
      connectionType: 'None'
      forceUpdate: true
      command: apply
      arguments: -f $(System.DefaultWorkingDirectory)/deployment/pipelines-files/kubernetes-files/elastic-agent/elastic-agent-win-daemonset.yaml
      secretType: 'generic'

  