jobs:
#JOB TO DEPLOY KUBERNETES RESOURCES USING THE CONFIGURED AGENT IN HUB VNET
#the agent name is devops-agent by default in every environment
- job: AKS_VantageDX_Resources_Job
  pool:
    name: $(agent-pool-name)
    demands:
    - agent.os -equals Linux
  
  variables:
    LICENSECODE: $[ dependencies.License_Generation_Job.outputs['licenseTask.LICENSECODE']]
  
  steps:        
  #take variables to be used from the shared Keyvault
  - task: AzureKeyVault@1
    displayName: Shared Azurekeyvault Variables Import
    inputs:
      azureSubscription: '$(azure-subscription)'
      KeyVaultName: '$(shared-keyvault)'
      SecretsFilter: '*'
      runAsPreJob: true

  #Retrieve the name of the variable that contains the name of the tenant's keyvault
  - task: AzureCLI@2
    displayName: Getting Tenant Keyvault name
    inputs:
      azureSubscription: '$(azure-subscription)'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        getvariable=$(az keyvault secret list --vault-name $(vaultsNamesKeyvault) --output table --query [].'name'| grep -w '$(CUSTOMERNAME)KVname')
        kvname=$(az keyvault secret show --name $getvariable --vault-name $(vaultsNamesKeyvault) --query 'value' | tr -d \'\")
        echo "##vso[task.setvariable variable=TENANTKV;]$kvname"

  #take variables to be used from the tenant Keyvault
  - task: AzureKeyVault@1
    displayName: Tenant Azurekeyvault Variables Import
    inputs:
      azureSubscription: '$(azure-subscription)'
      KeyVaultName: '$(TENANTKV)'
      SecretsFilter: '*'
      runAsPreJob: false
  
  #validate if namespace exists and creates a variable to be checked in the next tasks
  - task: AzureCLI@2
    displayName: Test AKS resources existence
    inputs:
      azureSubscription: '$(azure-subscription)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az login --identity
        az aks get-credentials --resource-group $(aks-resource-group) --name $(aks-cluster-name) --overwrite-existing --file /home/azureuser/.kube/config
        export KUBECONFIG=/home/azureuser/.kube/config
        kubelogin convert-kubeconfig -l msi
        if kubectl get namespace $(CUSTOMERNAME); then
          echo "##vso[task.setvariable variable=CreateNamespace;]false"
        else
          echo "##vso[task.setvariable variable=CreateNamespace;]true"
        fi
  
  #replace variables in kubernetes files using the input variables and also from the two keyvaults
  - task: replacetokens@5
    displayName: Replace variables in kubernetes templates
    inputs:
      rootDirectory: '$(System.DefaultWorkingDirectory)/deployment/pipelines-files/kubernetes-files/vantagedx'
      targetFiles: |
        configmap-cluster1.yaml
        secret-cluster1.yaml
        ingress-cluster1.yaml
      encoding: 'auto'
      writeBOM: true
      actionOnMissing: 'fail'
      keepToken: false
      tokenPrefix: '#{'
      tokenSuffix: '}#'
      verbosity: '$(DEBUG_REPLACETOKEN)'

  #creation of client's namespace in kubernetes if doesn't exist by checking the variable CreateNamespace created before
  - task: Kubernetes@1
    displayName: Create Tenant Namespace
    condition: eq(variables.CreateNamespace, True)
    inputs:
      connectionType: 'None'
      command: 'create'
      arguments: 'namespace $(CUSTOMERNAME)'
      secretType: 'generic'

  #creation of client's configmap in kubernetes
  - task: Kubernetes@1
    displayName: Create VantageDx shared Configmap
    inputs:
      connectionType: 'None'
      forceUpdateConfigMap: true
      namespace: '$(CUSTOMERNAME)'
      command: apply
      arguments: -f $(System.DefaultWorkingDirectory)/deployment/pipelines-files/kubernetes-files/vantagedx/configmap-cluster1.yaml
      secretType: 'generic'

  #creation of client's secret in kubernetes
  - task: Kubernetes@1
    displayName: Create VantageDx shared secret
    inputs:
      connectionType: 'None'
      forceUpdateConfigMap: true
      namespace: '$(CUSTOMERNAME)'
      command: apply
      arguments: -f $(System.DefaultWorkingDirectory)/deployment/pipelines-files/kubernetes-files/vantagedx/secret-cluster1.yaml
      secretType: 'generic'

  #creation of client's Ingress in kubernetes
  - task: Kubernetes@1
    displayName: Deploy Ingress file
    condition: and(succeeded(), eq(variables.CBMT, False))
    inputs:
      connectionType: 'None'
      forceUpdateConfigMap: true
      namespace: '$(CUSTOMERNAME)'
      command: apply
      arguments: -f $(System.DefaultWorkingDirectory)/deployment/pipelines-files/kubernetes-files/vantagedx/ingress-cluster1.yaml
      secretType: 'generic'

