---
parameters:
- name: environment
  displayName: Environment
  type: string
  default:
    azTenant1-env1
  values:
    - azTenant1-env1
    - azTenant2-env1

- name: tenantname
  displayName: Tenant Name
  type: string
- name: keycloakImageVersion
  displayName: Keycloak Image Version
  type: string
  default: 'v20220908.2'
- name: msmonitorImageVersion
  displayName: MSmonitor Image Version
  type: string
  default: '3.6.0.32672.32675'
- name: msm-agentImageVersion
  displayName: MSmonitor's MSM-Agent Manager Image Version
  type: string
  default: ' '
- name: ntwmonitorImageVersion
  displayName: iQ Image Version
  type: string
  default: '3.6.1.457'
- name: elasticSearchVersion
  displayName: Elastic Search Version
  type: string
  default: '7.17.5'

trigger: none
pr: none

variables:
- template: variables/environments/env-vars-${{ parameters.environment }}.yaml
- template: variables/pipelines/static/pipelines-vars-${{ parameters.environment }}.yaml
- template: variables/pipelines/runtime/deploy-input-vars.yaml
  parameters:
    tenantname: ${{ parameters.tenantname }}
    msmonitorImageVersion: ${{ parameters.msmonitorImageVersion }}
    msm-agentImageVersion: ${{ parameters.msm-agentImageVersion }}
    ntwmonitorImageVersion: ${{ parameters.ntwmonitorImageVersion }}
    keycloakImageVersion: ${{ parameters.keycloakImageVersion }}
    npvImageVersion: ${{ parameters.npvImageVersion }}
    elasticSearchVersion: ${{ parameters.elasticSearchVersion }}
    environment: ${{ parameters.environment }}



    
name: $(Date:yyyyMMdd)_TENANT=${{ parameters.tenantname }}_ENV=${{ parameters.environment }}

stages:
### CREATE TENANT KEYVAULT ###
- stage: job_keyvault_variables_creation
  condition: eq(variables.CBMT, false)
  jobs:
    - template: pipelines-jobs/deploy/vantagedx/create-keyvault-vantagedx.yml

### CREATE ELASTICSEARCH DEPLOYMENT ###
- stage: job_create_elasticsearch_deployment
  dependsOn: job_keyvault_variables_creation
  condition: and(succeeded(), eq(variables.DEPLOY_IQ, true))
  jobs:
    - template: pipelines-jobs/deploy/vantagedx/create-es-resources.yml

### VANTAGEDX SHARED CONFIGMAP CREATION ###
- stage: job_cluster1_shared_aks_resources_creation
  dependsOn: job_create_elasticsearch_deployment
  jobs:
    - template: pipelines-jobs/deploy/vantagedx/aks-vantagedx-resources.yml

### KEYCLOAK INFRASTRUCTURE CREATION AND CONFIGURATION ###
- stage: job_keycloak_infrastructure_configuration
  dependsOn: job_cluster1_shared_aks_resources_creation
  jobs:
    - template: pipelines-jobs/deploy/keycloak/configure-kc-resources.yml

### KEYCLOAK AKS RESOURCES DEPLOYMENT ###
- stage: job_keycloak_aks_deployment
  dependsOn: job_keycloak_infrastructure_configuration
  jobs:
    - template: pipelines-jobs/deploy/keycloak/deploy-aks-resources.yaml

### CREATE DNS RECORDS ###
- stage: job_cluster1_create_dns_record
  dependsOn: job_keycloak_aks_deployment
  jobs:
    - template: pipelines-jobs/deploy/vantagedx/create_dns_vantagedx.yml

### GET VARIABLES AND CONFIGURE INFRASTRUCTURE RESOURCES ###
- stage: job_configure_infrastructure_components
  dependsOn: job_cluster1_create_dns_record
  jobs:
    - template: pipelines-jobs/deploy/msmonitor/msmonitor-create-resources.yml
    
### GET VARIABLES AND CREATE MSmonitor KUBERNETES ELEMENTS ###
- stage: msmonitor_job_create_aks_resources
  dependsOn: job_configure_infrastructure_components
  jobs:
    - template: pipelines-jobs/deploy/msmonitor/aks-msmonitor-resources.yml

### GET iQ VARIABLES AND CONFIGURE INFRASTRUCTURE RESOURCES ###
- stage: ntwmonitor_job_configure_infrastructure_components
  dependsOn: msmonitor_job_create_aks_resources
  condition: and(succeeded(), eq(variables.DEPLOY_IQ, true))
  jobs:
    - template: pipelines-jobs/deploy/ntwmonitor/ntwmonitor-create-resources.yml

### GET VARIABLES AND CREATE IQ KUBERNETES ELEMENTS ###
- stage: ntwmonitor_job_create_aks_resources
  dependsOn: ntwmonitor_job_configure_infrastructure_components
  condition: and(succeeded(), eq(variables.DEPLOY_IQ, true))
  jobs:
    - template: pipelines-jobs/deploy/ntwmonitor/aks-ntwmonitor-resources.yml

### GET VERSION VARIABLES VALUE AND SEND IT TO ELASTICSEARCH ###
- stage: job_version_management_variables
  dependsOn: npv_deploy_application
  jobs:
    - template: pipelines-jobs/deploy/versionvariables/getversionvariables.yml
    
### Create tenant endpoint to monitor with heartbeat
- stage: deploy_heartbeat_endpoint
  dependsOn: job_version_management_variables
  jobs:
    - template: pipelines-jobs/deploy/vantagedx/aks-heartbeat-endpoint.yml
