---
parameters:
- name: environment
  displayName: Environment
  type: string
  default:
    azTenant1-env1
  values:
    - azTenant1-env1
    - azTenant2-env1

- name: tenantname
  displayName: Tenant Name
  type: string
- name: softDeleteKV
  displayName: Soft-Delete Keyvault
  type: string
  default:
    'false'
  values:
    - 'false'
    - 'true'
- name: purgeKV
  displayName: Purge Soft-Deleted Keyvault
  type: string
  default:
    'false'
  values:
    - 'false'
    - 'true'

trigger: none
pr: none

variables:
- template: variables/environments/env-vars-${{ parameters.environment }}.yaml
- template: variables/pipelines/static/pipelines-vars-${{ parameters.environment }}.yaml
- template: variables/pipelines/runtime/offboarding-input-vars.yaml
  parameters:
    tenantname: ${{ parameters.tenantname }}
    softDeleteKV: ${{ parameters.softDeleteKV }}
    purgeKV: ${{ parameters.purgeKV }}

name: $(Date:yyyyMMdd)_TENANT=${{ parameters.tenantname }}_ENV=${{ parameters.environment }}

stages:
### DELETE HEARTBEAT ENDPOINT ###
- stage: delete_heartbeat_endpoint
  jobs:
    - template: pipelines-jobs/offboarding/heartbeat-endpoint-removal.yml
    
### DELETE TENANT NAMESPACE IN KUBERNETES ###
- stage: namespace_removal
  jobs:
    - template: pipelines-jobs/offboarding/namespace-removal.yml

### DELETE RECORD A FROM DNS ZONE ###
- stage: record_dns_removal
  dependsOn: namespace_removal
  jobs:
    - template: pipelines-jobs/offboarding/dns-record-removal.yml

### DELETE RABBITMQ COMPONENTS ###
- stage: rabbitmq_resources_removal
  dependsOn: record_dns_removal
  jobs:
    - template: pipelines-jobs/offboarding/rabbitmq-resources-removal.yml

### DELETE ELASTICSEARCH DEPLOYMENT ###
- stage: es_deployment_removal
  dependsOn: rabbitmq_resources_removal
  jobs:
    - template: pipelines-jobs/offboarding/es-deployment-removal.yml

### DELETE SQL DB RESOURCES ###
- stage: sql_db_removal
  dependsOn: es_deployment_removal
  jobs:
    - template: pipelines-jobs/offboarding/sql-db-removal.yml

### DELETE POSTGRES SQL DB RESOURCES ###
- stage: postgres_db_removal
  dependsOn: sql_db_removal
  jobs:
    - template: pipelines-jobs/offboarding/postgresql-removal.yml

### SOFT DELETE KEYVAULT ###
- stage: delete_keyvault
  dependsOn: postgres_db_removal
  condition: and(succeeded(), eq(variables.SOFT_DELETE_KEYVAULT, true))
  jobs:
    - template: pipelines-jobs/offboarding/delete-keyvault.yml
