trigger: none
pr: none

stages:
- stage: update_ingress_config
  jobs:
  - job: Ingress_controller_config
    pool:
      name: $(agent-pool-name)
      demands:
      - agent.os -equals Linux
    
    steps:
    - task: Bash@3
      displayName: Get aks credentials
      inputs:
        targetType: 'inline'
        Script: |
          az login --identity
          az account set --subscription $(azure-subscription-id)
          az aks get-credentials --resource-group $(AKS_RG) --name $(AKS_CLUSTER) --overwrite-existing --file /home/azureuser/.kube/config
          export KUBECONFIG=/home/azureuser/.kube/config
          kubelogin convert-kubeconfig -l msi
  
    - task: Kubernetes@1
      displayName: Deploy Nginx ConfigMap
      inputs:
        connectionType: 'None'
        forceUpdateConfigMap: true
        namespace: 'ingress-nginx-cluster1'
        command: apply
        arguments: -f $(System.DefaultWorkingDirectory)/deployment/pipelines-files/kubernetes-files/nginx-ingress/nginx-config.yaml
        secretType: 'generic'
