aurelien_gaming_name: "Aurel-Gaming"
aurelien_gaming_ip: "192.168.1.4"
remote_desktop_port: "3535"
firefox_extension_id_videoDownloadHelper: "{b9db16a4-6edc-47ec-a1f4-b86292ed211d}"
firefox_extension_id_uBlockOrigin: "uBlock0@raymondhill.net"
firefox_extension_id_downThemAll: "{DDC359D1-844A-42a7-9AA1-88A850A938A8}"