---
  # - name: Import Bitwarden conf
  #   ansible.builtin.template:
  #       src: /share/git/resources/softwares_configs/config-files/bitwarden/data.json
  #       dest: '{{ appData_user_directory }}\Bitwarden'
  #       force: false
  #   when: ansible_facts['system'] == "Win32NT" and ansible_hostname == "Aurel-Gaming"

  - name: Create Firefox/Distribution directory
    ansible.windows.win_file:
      path: C:\Program Files\Mozilla Firefox\distribution
      state: directory
    when: ansible_facts['system'] == "Win32NT"
    
  - name: Import Firefox Policies
    ansible.builtin.template:
        src: /share/git/resources/softwares_configs/config-files/Firefox/policies.json
        dest: C:\Program Files\Mozilla Firefox\distribution
        force: true
    when: ansible_facts['system'] == "Win32NT"

  # - name: Add Firefox Policies
  #   ansible.windows.win_regedit:
  #       path: 'HKLM:\SOFTWARE\Policies\Mozilla\Firefox\3rdparty\"{ bitwarden_firefox_extension_id }}'
  #       name: base
  #       data: "{{ bitwarden_server_url }}"
  #       type: expandstring
  #   when: ansible_facts['system'] == "Win32NT"

  - name: Import Firefox Policies
    ansible.builtin.template:
        src: /share/git/resources/softwares_configs/config-files/Firefox/policies.json
        dest: /usr/lib/firefox/distribution
        force: true
    vars:
      ansible_become: yes
      ansible_become_password: "{{ sudo_pwd }}"
    when: ansible_facts['system'] == "Linux"

  # - name: Import GoG conf
  #   ansible.builtin.template:
  #       src: /share/git/resources/softwares_configs/config-files/GoGGalaxy/config.json
  #       dest: '{{ localAppData_user_directory }}\GOG.com\Galaxy\Configuration'
  #       force: false
  #   when: ansible_facts['hostname'] == "Aurel-Gaming"
    
  # - name: Import Ubisoft Connect Config
  #   ansible.builtin.template:
  #       src: /share/git/resources/softwares_configs/config-files/UbisoftConnect/settings.yaml
  #       dest: '{{ localAppData_user_directory }}\Ubisoft Game Launcher'
  #       force: false
  #   when: ansible_facts['hostname'] == "Aurel-Gaming"

