---
  - name: Import Bitwarden conf
    ansible.builtin.template:
        src: /share/git/resources/softwares_configs/config-files/bitwarden/data.json
        dest: C:\Users\{{ ansible_user }}\AppData\Roaming\Bitwarden
        force: false
    when: ansible_facts['system'] == "Windows"

  - name: Import Bitwarden conf
    ansible.builtin.template:
        src: /share/git/resources/softwares_configs/config-files/bitwarden/data.json
        dest: /home/aurel/.config/Bitwarden
        force: false
    when: ansible_facts['system'] == "Linux"

  - name: Import Firefox Policies
    ansible.builtin.template:
        src: /share/git/resources/softwares_configs/config-files/Firefox/policies.json
        dest: /usr/lib/firefox/distribution
        force: true
    vars:
      ansible_become: yes
      ansible_become_password: "{{ sudo_pwd }}"
    when: ansible_facts['system'] == "Linux"


  - name: Import GoG conf
    ansible.builtin.template:
        src: /share/git/resources/softwares_configs/config-files/config.json
        dest: C:\Users\{{ ansible_user }}\AppData\Local\GOG.com\Galaxy\Configuration
        force: false
    when: ansible_facts['hostname'] == "Aurel-Gaming"
    
  - name: Import Ubisoft Connect Config
    ansible.builtin.template:
        src: /share/git/resources/softwares_configs/config-files/UbisoftConnect/settings.yaml
        dest: 'C:\Users\{{ ansible_user }}\AppData\Local\Ubisoft Game Launcher'
        force: false
    when: ansible_facts['hostname'] == "Aurel-Gaming"

  - name: Import RDP Remina Conf
    ansible.builtin.template:
        src: /share/git/resources/softwares_configs/config-files/Remmina/rdp.remmina
        dest: /home/aurel/.local/share/remmina/group_rdp_rdp-{{ ansible_facts.hostname }}.remmina
        force: false
    when: ansible_facts['system'] == "Linux"
