---
- name: Deploy Blog maman
  hosts: macbookair-aurelien.local
  vars_files:
    - ../Variables/macbookair-aurelien.yml
    - ../Variables/macbookair-aurelien-secrets.yml

  tasks:
  - name: Check Python requests is installed
    ansible.builtin.pip:
      name: requests
      state: present

  - name: Install docker python package
    ansible.builtin.pip:
      name: docker

  - name: Replace credsStore by credStore (fix docker-credential-desktop issue)
    ansible.builtin.replace:
      path: /Users/{{ user_name }}/.docker/config.json
      regexp: 'credsStore'
      replace: "credStore"

  - name: Log into DockerHub
    community.docker.docker_login:
      username: '{{ dockerHub_username }}'
      password: '{{ dockerHub_password }}'

  - name: Deploy fonduededeco container
    community.docker.docker_container:
      name: '{{ container_name_fonduededeco }}'
      image: '{{ image_name_fonduededeco }}'
      state: started
      published_ports: 8080:80
