all:
  children:
    linux_hosts:
      hosts:
        nas.eonelia.fr:
          ansible_connection: ssh
          ansible_host: 192.168.2.114
          ansible_port: 3434
          ansible_user: a.busutil
        arch-linux-laptop:
    macos_hosts:
      hosts:
        macbook-m2:
        macbook-air-aurelien:
    windows_hosts:
      hosts:
        w11-vm-aurel:
        aurelien-gaming:
    proxmox_hosts:
      hosts:
        wyse-proxmox:
