---
- name: Restart headscale
  ansible.builtin.systemd:
    name: headscale
    state: restarted
  when: not ansible_check_mode

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
