---
  - name: Remove epiphany (GNOME Default Browser)
    community.general.pacman:
      name: epiphany
      state: absent
    vars:
      ansible_become: yes
      ansible_become_pass: "{{ sudo_pwd }}"