---
  - name: Copy /boot/loader/entries/arch.conf to home
    ansible.builtin.copy:
      src: /boot/loader/entries/arch.conf
      dest: /home/aurel
      mode: preserve
      remote_src: yes
    vars:
      ansible_become: yes
      ansible_become_pass: "{{ sudo_pwd }}"

  - name: Add mem_sleep_default=deep at the end of boot entry (for XPS 7590)
    ansible.builtin.replace:
      path: /home/aurel/arch.conf
      regexp: '(options.+)'
      replace: '\1 mem_sleep_default=deep'
    vars:
      ansible_become: yes
      ansible_become_pass: "{{ sudo_pwd }}"  

  - name: Copy new arch.conf to /boot/loader/entries
    ansible.builtin.copy:
      src: /home/aurel/arch.conf
      dest: /boot/loader/entries
      mode: preserve
      remote_src: yes
    vars:
      ansible_become: yes
      ansible_become_pass: "{{ sudo_pwd }}"

  - name: Enable service bluetooth
    ansible.builtin.systemd:
      name: bluetooth
      enabled: yes
    vars:
      ansible_become: yes
      ansible_become_pass: "{{ sudo_pwd }}"

  - name: Enable service CUPS (Printer)
    ansible.builtin.systemd:
      name: cups
      enabled: yes
    vars:
      ansible_become: yes
      ansible_become_pass: "{{ sudo_pwd }}"

  - name: Download DashToDock
    ansible.builtin.get_url:
      url: https://extensions.gnome.org/extension-data/dash-to-dockmicxgx.gmail.com.v75.shell-extension.zip
      dest: /home/aurel/Downloads

  - name: Install DashToDock
    ansible.builtin.script: /share/git/resources/Ansible/Roles/Linux/Laptop/scripts/install_dashtodock.sh



  # - name: Create the `aur_builder` user
  #   ansible.builtin.user:
  #     name: aur_builder
  #     create_home: yes
  #     group: wheel
  #   vars:
  #     ansible_become: yes
  #     ansible_become_password: "{{ sudo_pwd }}"

  # - name: Allow the `aur_builder` user to run `sudo pacman` without a password
  #   ansible.builtin.lineinfile:
  #     path: /etc/sudoers.d/11-install-aur_builder
  #     line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
  #     create: yes
  #     validate: 'visudo -cf %s'
  #   vars:
  #     ansible_become: yes
  #     ansible_become_password: "{{ sudo_pwd }}"

  # - name: Copy /boot/loader/entries/arch.conf to home
  #   ansible.builtin.copy:
  #     src: /boot/loader/entries/arch.conf
  #     dest: /home/aurel
  #     mode: preserve
  #     remote_src: yes
  #   vars:
  #     ansible_become: yes
  #     ansible_become_pass: "{{ sudo_pwd }}"




