#Get secrets from AWS Secret Manager and store to Ansible variables
webdav_username: "{{ lookup('amazon.aws.aws_secret', 'Ansible.webdav_username', nested=true) }}"
webdav_password: "{{ lookup('amazon.aws.aws_secret', 'Ansible.webdav_password', nested=true) }}"
remote_local_user_name_password: "{{ lookup('amazon.aws.aws_secret', 'Ansible.ag_remote_local_user_name_password', nested=true) }}"
microsoft_account_email: "{{ lookup('amazon.aws.aws_secret', 'Ansible.microsoft_account_email', nested=true) }}"
microsoft_account_password: "{{ lookup('amazon.aws.aws_secret', 'Ansible.microsoft_account_password', nested=true) }}"
ubisoft_connect_username: "{{ lookup('amazon.aws.aws_secret', 'Ansible.ubisoft_connect_username', nested=true) }}"
ubisoft_connect_password: "{{ lookup('amazon.aws.aws_secret', 'Ansible.ubisoft_connect_password', nested=true) }}"
