---
- name: Remove Blog maman (fonduededeco container)
  hosts: macbook-air-aurelien
  gather_facts: false

  tasks:
    - name: Stop the container
      community.docker.docker_container:
        name: "{{ container_name_fonduededeco }}"
        state: stopped

    - name: Remove the container
      community.docker.docker_container:
        name: "{{ container_name_fonduededeco }}"
        state: absent
