jobs:
- job: job_record_dns_removal
  pool:
    vmImage: 'windows-2019'

  steps:
  #take variables to be used from the shared Azure Keyvault
  - task: AzureKeyVault@1
    displayName: Shared Azurekeyvault Variables Import
    inputs:
      azureSubscription: '$(azure-subscription)'
      KeyVaultName: '$(shared-keyvault)'
      SecretsFilter: '*'
      runAsPreJob: true

  #delete record A from DNS zone
  - task: AzureCLI@2
    displayName: Delete A Record in DNS Zone
    inputs:
      azureSubscription: '$(dns-azure-subscription)'
      scriptType: ps
      scriptLocation: inlineScript
      inlineScript: |
        $recordExists=$(az network dns record-set a list -g $(dnsZoneRG) -z $(cluster1CL1DnsZoneName) | select-string -pattern '$(CUSTOMERNAME)')
        if (![string]::IsNullOrEmpty($recordExists)) {
          Write-Host "Record exists... Deleting it"
          az network dns record-set a delete -g $(dnsZoneRG) -z $(cluster1CL1DnsZoneName) -n $(CUSTOMERNAME) --yes
        }else {
          Write-Host "Record doesn't exist... Nothing to do"
        }