jobs:
- job: job_rabbitmq_resources_removal
  pool:
    vmImage: 'windows-2019'

  steps:
  #take variables to be used from the shared Keyvault
  - task: AzureKeyVault@1
    displayName: Shared Azurekeyvault Variables Import
    inputs:
      azureSubscription: '$(azure-subscription)'
      KeyVaultName: '$(shared-keyvault)'
      SecretsFilter: '*'
      runAsPreJob: true

  #Retrieve the name of the variable that contains the name of the tenant's keyvault
  - task: AzureCLI@2
    displayName: Getting Tenant Keyvault name
    inputs:
      azureSubscription: '$(azure-subscription)'
      scriptType: ps
      scriptLocation: inlineScript
      inlineScript: |
        $getvariable = az keyvault secret list --vault-name $(vaultsNamesKeyvault) --output table --query [].'name'| Select-String -pattern '^$(CUSTOMERNAME)KVname$'
        $kvname = az keyvault secret show --name $getvariable --vault-name $(vaultsNamesKeyvault) --query 'value'
        $kvname = $kvname.Trim('"','''')
        Write-Host ("##vso[task.setvariable variable=TENANTKV;]$kvname")

  #take variables to be used from the tenant Keyvault
  - task: AzureKeyVault@1
    displayName: Tenant Azurekeyvault Variables Import
    inputs:
      azureSubscription: '$(azure-subscription)'
      KeyVaultName: '$(TENANTKV)'
      SecretsFilter: '*'
      runAsPreJob: false
  
  #replace variables in sql script
  - task: replacetokens@5
    displayName: Values Replacements in Windows Script
    inputs:
      targetFiles: |
        deployment/pipelines-files/windows-files/scripts/powershell/delete-rabbitmq-resources.ps1
      encoding: 'auto'
      writeBOM: true
      actionOnMissing: 'fail'
      keepToken: false
      tokenPrefix: '#{'
      tokenSuffix: '}#'
  
  #execute script
  - powershell: ./deployment/pipelines-files/windows-files/scripts/powershell/delete-rabbitmq-resources.ps1
    displayName: Delete vhost and user associated