---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit-sa
  namespace: logging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit-read
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - pods
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit-read
subjects:
  - kind: ServiceAccount
    name: fluent-bit-sa
    namespace: logging
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-elastic-cloud
  namespace: logging
data:
  FLUENT_ELASTIC_CLOUD_ID: #{FLUENT_ELASTIC_CLOUD_ID}#
  FLUENT_ELASTIC_CLOUD_AUTH: #{FLUENT_ELASTIC_CLOUD_AUTH}#
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-configmap
  labels:
    app: fluent-bit
  namespace: logging
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         5
        Log_Level     warn
        Daemon        off
        Parsers_File  parsers.conf
    # Windows logs
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              c:\var\log\containers\*ntwmonitor*.log
        Parser            simple_cri_parser
        DB                /var/log/flb_kube1.db
        Refresh_Interval  60
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              c:\var\log\containers\*msm-agent*.log
        Parser            simple_cri_parser
        DB                /var/log/flb_kube1.db
        Refresh_Interval  60
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              c:\var\log\containers\*msmonitor*.log
        Parser            simple_cri_parser
        DB                /var/log/flb_kube1.db
        Refresh_Interval  60
    # linux logs
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*npv*.log
        Parser            simple_cri_parser
        DB                /var/log/flb_kube1.db
        Refresh_Interval  60
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              ,/var/log/containers/*keycloak*.log
        Parser            simple_cri_parser
        DB                /var/log/flb_kube1.db
        Refresh_Interval  60
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*nginx*.log
        Parser            simple_cri_parser
        DB                /var/log/flb_kube1.db
        Refresh_Interval  60

    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Merge_Log           Off
        DNS_Retries         10

    # match only those logs that have multilines to merge
    [FILTER]
        name                  multiline
        match                 *ntwmonitor*
        multiline.key_content log
        multiline.parser      both-multiline-parser
    [FILTER]
        name                  multiline
        match                 *msm-agent*
        multiline.key_content log
        multiline.parser      both-multiline-parser
    [FILTER]
        name                  multiline
        match                 *npv-server*
        multiline.key_content log
        multiline.parser      both-multiline-parser
    [FILTER]
        name                  multiline
        match                 *keycloak*
        multiline.key_content log
        multiline.parser      both-multiline-parser

    [FILTER]
        Name                record_modifier
        Match               kube.*
        Remove_key          time
        Remove_key          stream

    [OUTPUT]
        Name  es
        Match *
        cloud_id ${FLUENT_ELASTIC_CLOUD_ID}
        cloud_auth ${FLUENT_ELASTIC_CLOUD_AUTH}
        tls On
        tls.verify Off
        Suppress_Type_Name On
  parsers.conf: |
    [PARSER]
        Name        simple_cri_parser
        Format      regex
        Regex       /^(?<time>\d+-\d+-\d+T[\d|:|.]+Z) (stdout|stderr) (F|P) (?<log>.*)/
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
    [MULTILINE_PARSER]
        name          both-multiline-parser
        type          regex
        key_content   log
        flush_timeout 1000
        rule      "start_state" "/^(\d+-\d+-\d+ \S{8,13} .*)/"  "cont"
        rule      "cont"        "/^(?:(?!\d\d\d\d\-\d\d-\d\d)).*/"  "cont"

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: fluent-bit
  name: fluent-bit-windows
  namespace: logging
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      tolerations:
        - key: "windows"
          operator: "Equal"
          value: "2019"
          effect: "NoSchedule"
      containers:
        - image: #{CONTAINER_REGISTRY}#/fluent-bit:1.8.11
          imagePullPolicy: IfNotPresent
          name: fluent-bit
          command: [fluent-bit]
          args:
            - --config
            - /fluent-bit/etc/fluent-bit.conf
          workingDir: /fluent-bit/etc
          volumeMounts:
            - mountPath: /fluent-bit/etc
              name: fluent-bit-config
            - mountPath: /var/log
              name: varlog
              readOnly: false
            - mountPath: /ProgramData/docker/containers
              name: dockercontainers
              readOnly: true
          envFrom:
            - configMapRef:
                name: configmap-elastic-cloud
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: dockercontainers
          hostPath:
            path: /ProgramData/docker/containers
        - configMap:
            defaultMode: 420
            name: fluent-bit-configmap
          name: fluent-bit-config
      serviceAccountName: fluent-bit-sa
  updateStrategy:
    type: RollingUpdate
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: fluent-bit
  name: fluent-bit-linux
  namespace: logging
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - image: #{CONTAINER_REGISTRY}#/fluent-bit-linux:1.8.11
          imagePullPolicy: IfNotPresent
          name: fluent-bit
          volumeMounts:
            - mountPath: /fluent-bit/etc
              name: fluent-bit-config
            - mountPath: /var/log
              name: varlog
              readOnly: false
            - mountPath: /var/lib/docker/containers
              name: varlibdockercontainers
              readOnly: true
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/
          envFrom:
            - configMapRef:
                name: configmap-elastic-cloud
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - configMap:
            defaultMode: 420
            name: fluent-bit-configmap
          name: fluent-bit-config
      serviceAccountName: fluent-bit-sa
  updateStrategy:
    type: RollingUpdate
