apiVersion: v1
kind: Service
metadata:
  name: service-msmonitor
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: port80
  selector:
    app: msmonitor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msmonitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msmonitor
  template:
    metadata:
      labels:
        app: msmonitor
        customer: '#{CUSTOMERNAME}#'
    spec:
      nodeSelector:
        "kubernetes.io/os": windows
        pods: 'msmonitor'
      containers:
      - name: msmonitor
        image: "#{azureContainerRegistry}#/#{IMAGE_REPO_MSmonitor}#:#{MSmonitor_IMAGE_VERSION}#"
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "500m"
            memory: "2Gi"
          requests:
            cpu: "50m"
            memory: "500Mi"
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: configmap-global
        - configMapRef:
            name: configmap-msmonitor
        - secretRef:
            name: secret-global
        - secretRef:
            name: secret-msmonitor
