jobs:
 #JOB TO DEPLOY version variables in elasticsearch
  - job: version_management_job
    pool:
      name: $(agent-pool-name)
      demands:
      - agent.os -equals Linux
      
    steps:
      - task: AzureKeyVault@1
        displayName: Shared Azurekeyvault Variables Import
        inputs:
          azureSubscription: '$(azure-subscription)'
          KeyVaultName: '$(shared-keyvault)'
          SecretsFilter: '*'
          runAsPreJob: true

      - task: Bash@3
        displayName: deploy version variables
        inputs:
          targetType: 'inline'
          script: |
            export var=$(date --utc +%s%3N) 

            versionmgmt()
            {
              cat <<EOF
                    
                  {
                    "msmonitorversion": "$(MSmonitor_IMAGE_VERSION)",
                    "ntwmonitorversion": "$(IQ_IMAGE_VERSION)",
                    "keycloakversion": "$(KEYCLOAK_IMAGE_VERSION)",
                    "npvversion": "$(NPV_IMAGE_VERSION)",
                    "esversion": "$(ESupdatedVersion)",
                    "cluster1instancename": "$(CUSTOMERNAME)",
                    "environment": "$(ENVIRONMENT)",
                    "@timestamp": "$var"

                  }
            EOF
            }     
            curl -X POST "$(ES_OBSERVABILITY_URL)" -H "Authorization: Apikey $(esObservabilityApiKey)" -H 'Content-Type: application/json' -d "$(versionmgmt)"
              
       
 
 