---
- name: Main Aurelien Gaming Playbook
  hosts: 
    - macbook-air-aurelien
  gather_facts: true
  vars_files:
    - Roles/Linux/Laptop/vars/linux-laptop-secrets.yml
    - Roles/Common/vars/common_secrets.yml
    - Roles/Common/vars/common_vars.yml

  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts