---
- name: Uninstall Windows AppX bloatware
  hosts: aurelien-gaming
  gather_facts: yes

  tasks:
    - ansible.builtin.include_role:
        name: windows_gaming
        tasks_from: softwares_uninstall.yml
