---
- name: Main Aurelien Gaming Playbook
  hosts: 
    - windows_hosts
  gather_facts: yes  

  vars_files:
    - Roles/Windows/vars/aurelien-gaming-vars-secrets.yml
    - Roles/Windows/vars/aurelien-gaming-vars.yml
    - Roles/Windows/vars/w11-vm-vars-secrets.yml
    - Roles/Windows/vars/w11-vm-vars.yml
    - Roles/Common/vars/common_secrets.yml
    - Roles/Windows/vars/common_vars.yml
    - Roles/Common/vars/common_vars.yml   



  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts
        
    - name: Include windows_settings.yml
      ansible.builtin.import_tasks: Roles/Windows/tasks/windows_settings.yml

    - name: Include user_location.yml
      ansible.builtin.import_tasks: Roles/Windows/tasks/registry_keys_location.yml
      when: ansible_hostname == "Aurel-Gaming"

    - name: Include check_softwares_installed.yml
      ansible.builtin.import_tasks: Roles/Windows/tasks/check_softwares_installed.yml

    - name: Include download_Softwares.yml
      ansible.builtin.import_tasks: Roles/Windows/tasks/download_Softwares.yml

    - name: Include install_Softwares.yml
      ansible.builtin.import_tasks: Roles/Windows/tasks/install_Softwares.yml

    - name: Include settings_softwares
      ansible.builtin.import_tasks: Roles/Common/tasks/settings_softwares.yml

    - name: Include uninstall_softwares
      ansible.builtin.import_tasks: Roles/Windows/tasks/uninstall_Softwares.yml

    - name: Include Check_Softwares_versions
      ansible.builtin.import_tasks: Roles/Windows/tasks/check_softwares_versions.yml

    - name: Include install_ms_store_apps
      ansible.builtin.import_tasks: Roles/Windows/tasks/install_ms_store_apps.yml
    