---
  - name: Install 7Zip
    win_command: C:\Windows\System32\msiexec.exe /i C:\temp\7z.msi /qn /norestart
    when: Sevenzip_installed.exists == false

  - name: Install Firefox
    win_command: C:\Windows\System32\msiexec.exe /i C:\temp\Firefox.msi /qb /norestart
    when: Firefox_installed.exists == false

  - name: Install Nvidia Drivers
    win_command: C:\temp\Nvidia.exe /s /norestart
    register: result
    when: ansible_hostname == "Aurel-Gaming" and Nvidia_installed.exists == false

  - name: Install Nvidia Drivers
    win_command: C:\temp\NvidiaGeforceExperience.exe /s
    register: result
    when: ansible_hostname == "Aurel-Gaming" and Nvidia_Geforce_Experience_installed == false

# #Reboot computer
#   - name: Reboot Gaming
#     ansible.windows.win_reboot:
#           test_command: 'exit (Get-Service -Name WinRM).Status -ne "Running"'
#     when: ansible_hostname == "Aurel-Gaming" and result.stdoutlines

#Install Ubisoft Connect
  - name: Install Ubisoft Connect via win_command
    win_command: C:\temp\UbisoftConnect.exe /S
    when: UbisoftConnect_installed.exists == false

#Install EA App
  - name: Install EA App via win_command
    win_command: C:\temp\EaApp.exe /SILENT /NORESTART
    when: EAApp_installed.exists == false

# #Add EAApp to Start Programs
#   - name: Create EAApp shortcut to Start Programs
#     community.windows.win_shortcut:
#       src: C:\Program Files\Electronic Arts\EA Desktop\EA Desktop\EALauncher.exe
#       dest: '{{ startup_user_directory }}\EALauncher.lnk'
#       icon: C:\Program Files\Electronic Arts\EA Desktop\EA Desktop\EALauncher.exe,0
#       windowstyle: 'minimized'
#     when: EAApp_installed.exists == true

#Run EA App as Administrator
  - name: Add "Run as Admin" flag to EAApp
    ansible.windows.win_regedit:
      path: HKLM:\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers
      name: C:\Program Files\Electronic Arts\EA Desktop\EA Desktop\EADesktop.exe
      data: RUNASADMIN
      type: string

#Install Epic Launcher
  - name: Ensure Epic is installed via win_command
    win_command: C:\Windows\System32\msiexec.exe /i C:\temp\Epic.msi /qb /norestart
    when: Epic_installed.exists == false

#Install Bitwarden
  - name: Install Bitwarden
    win_command: C:\temp\bitwarden.exe /allusers /S
    when: Bitwarden_installed.exists == false

  - name: Replace Synology Config
    ansible.windows.win_powershell:
      script: |
        $original_file = /share/git/resources/softwares_configs/config-files/SynologyDrive/config_win.json
        $destination_file =  /share/git/resources/softwares_configs/config-files/SynologyDrive/config_win_prepared.json
        (Get-Content $original_file) | Foreach-Object {
            $_ -replace '#{nas_url}#', '{{ nas_username }}' `
              -replace '#{nas_username}#', '{{ nas_username }}' `
              -replace '#{nas_password}#', '{{ nas_password }}' `
              -replace '#{sync_local_path}#', '{{ root_user_directory }}\Vault' `
              -replace '#{backup_root_directory}#', '{{ root_user_directory }}' `
            } | Set-Content $destination_file
        Get-Content $destination_file

#Install Synology Drive Client
  - name: Install Synology Drive Client
    win_command: C:\Windows\System32\msiexec.exe /i C:\temp\SynologyDrive.msi /qn CONFIGPATH="/share/git/resources/softwares_configs/config-files/SynologyDrive/config_win_prepared.json" /norestart
    when: SynoDriveClient_installed.exists == false

#Install Steam
  - name: Install Steam
    win_command: C:\temp\Steam.exe /S
    when: Steam_installed.exists == false

#Install GoG
  - name: Install GoG Galaxy 2
    win_command: C:\temp\GoG.exe /verysilent
    when: GoG_installed.exists == false

#Install Crystal Disk Info
  - name: Install CrystalDiskInfo
    win_command: C:\temp\Crystaldiskinfo.exe /VERYSILENT /NORESTART
    when: CrystalDiskInfo_installed.exists == false


  # - name: Uninstall WindowsAppxPackages
  #   ansible.windows.win_package:
  #       product_id: "{{ item }}"
  #       state: present
  #   loop:
  #       - Microsoft.GamingServices

##################################W11-VM-Aurel Softwares##################################
#Unzip Captvty
  - name: Unzip Captvty zip
    win_unzip:
      src: C:\Users\Aurel\Downloads\captvty-2.9.9.zip
      dest: C:\Captvty
    when: ansible_hostname == "W11-VM-Aurel"

#Install Windows ADK  
  - name: Install Windows ADK
    win_command: C:\temp\adk.exe /quiet /installpath c:\ADK /features OptionId.ImagingAndConfigurationDesigner
    when: ansible_facts['netbios_name'] == "W11-Aurel-VM"

#Install Notepad++  
  - name: Install Notepad++
    win_command: C:\temp\Notepad++.exe /S

#Install VLC
  - name: Install VLC
    win_command: C:\temp\vlc.exe /S
# #Install Rockstar Game Social Club
#   - name: Install RockStar Game Social Club
#     win_command: C:\temp\Rockstar.exe /S

