---
  - name: Remove TightVNC as a Service
    win_shell: |
        Remove-Item -Type Directory "C:\Program Files\TightVNC"


  - name: Remove registry path MyCompany (including all entries it contains)
    ansible.windows.win_regedit:
      path: HKLM:\Software\TightVNC
      state: absent
      delete_key: yes

  - name: Remove registry path MyCompany (including all entries it contains)
    ansible.windows.win_regedit:
      path: HKCU:\Software\TightVNC
      state: absent
      delete_key: yes

