#Github Action to run the Debian-Ansible container and start Ansible to manager targets

on:
  workflow_dispatch:
#Add inputs parameter will be use by the pipeline. Can be mendatory.
    inputs:
      python_version:
        type: string
        description: Python Version you want to use in the Debian-Ansible container
        required: true

jobs:
  start-ansible:
    name: run ansible container
    runs-on: self-hosted
    
    steps:
#Checkout the repo to have all files needed
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Get secrets by name and by ARN
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          secret-ids: |
            arn:aws:secretsmanager:eu-west-3:850204412331:secret:Ansible-gTAmY1
          parse-json-secrets: true

#Check the runner OS to start docker by the right way
      - name: Start docker on macOS
        if: runner.os == 'macOS'
        run: open -a docker && sleep 10

      - name: Ensure docker daemon is running on Linux
        if: runner.os == 'Linux'
        run: |
            until [ $(sudo systemctl is-active docker) = active ]
              do
                sudo systemctl start containerd docker
                sleep 3;
              done
            echo -e "Service Containerd & Docker are started and active"

      - name: Docker login
        run: sudo docker login -u {{ env.ANSIBLE_DOCKER_HUB_USERNAME }} -p {{ env.ANSIBLE_DOCKER_HUB_PASSWORD}}

#Build the container and push it to the docker registry
      - name: Build and push Debian-Ansible image
        uses: docker/build-push-action@v3.3.0
        with:
          file: ${{ github.workspace }}/Containers/Linux/Debian-Ansible/Ansible.dockerfile
          push: true
          tags: catskan/debian-ansible:amd64-${{ github.run_number }}
          labels: 'python-Version:${{ inputs.python_version }}'
          context: .
          build-args: python_version=${{ inputs.python_version }}