#Github Action to run the Debian-Ansible container and start Ansible to manager targets

on:
  workflow_dispatch:
#Add inputs parameter will be use by the pipeline. Can be mendatory.
    inputs:
      python_version:
        type: string
        description: Python Version you want to use in the Debian-Ansible container
        required: true

jobs:
  start-ansible:
    name: run ansible container
    runs-on: self-hosted
    
    steps:
#Checkout the repo to have all files needed
      - name: Checkout
        uses: actions/checkout@v3

#Check the runner OS to start docker by the right way
      - name: Start docker on macOS
        if: runner.os == 'macOS'
        run: open -a docker && sleep 10

      - name: Ensure docker daemon is running on Linux
        if: runner.os == 'Linux'
        run: |
            until [ $(sudo systemctl is-active docker) = active ]
              do
                sudo systemctl start containerd docker
                sleep 3;
              done
            echo -e "Service Containerd & Docker are started and active"

      - name: Docker login
        run: sudo docker login
        
#Build the container and push it to the docker registry
      - name: Build and push Debian-Ansible image
        uses: docker/build-push-action@v3.3.0
        with:
          file: ${{ github.workspace }}/Containers/Linux/Debian-Ansible/Ansible.dockerfile
          push: true
          tags: catskan/debian-ansible:${{ runner.os }}-${{ github.run_number }}
          labels: 'python-Version:${{ inputs.python_version }}'
          context: .
          build-args: python_version=${{ inputs.python_version }}