#Github Action to run the Debian-Ansible container and start Ansible to manager targets

on:
  workflow_dispatch:
  
jobs:
  start-ansible:
    name: run ansible container
    runs-on: self-hosted
    
    steps:
      - name: Show the OS
        run: echo $RUNNER_OS $GITHUB_WORKSPACE

      - name: Start docker on macOS
        if: runner.os == 'macOS'
        run: open -a docker && sleep 10


      - name: "Ensure docker daemon is running on Linux"
        if: runner.os == 'Linux'
        run: |
            until [ $(systemctl is-active containerd docker) = active ]
              do
                systemctl start containerd docker
                sleep 3;
              done
            echo -e "Service Containerd & Docker are started and active"
        
      - name: Build and push Debian-Ansible image
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@37abcedcc1da61a57767b7588cb9d03eb57e28b3
        uses: docker/build-push-action@v3.3.0
        with:
          file: $HOME/git/resources/Containers/Linux/Debian-Ansible/Ansible.dockerfile
          push: true
          tags: catskan.dockerhub.io/debian-ansible:v1