#Github Action to run the Debian-Ansible container and start Ansible to manager targets

on:
  workflow_dispatch:
  
jobs:
  start-ansible:
    name: run ansible container
    runs-on: self-hosted
    
    steps:
      - name: "Ensure docker daemon is running"
        run: |
          if [ "$(systemctl is-active containerd)" == "active" ]
          then
            echo "Containerd is active" ;;
          elif [ "$(systemctl is-active containerd)" == "inactive" ]
            echo "Containerd is inactive" ;;
          fi
