#Github Action to run the Debian-Ansible container and start Ansible to manager targets

on:
  workflow_dispatch:

  
jobs:
  start-ansible:
    name: run ansible container
    runs-on: self-hosted
    
    steps:
#Checkout the repo to have all files needed
      - name: Checkout
        uses: actions/checkout@v3

      - name: Replace string in Vagrant file
        if: runner.os == 'macOS'
        uses: datamonsters/replace-action@v2
        with:
          files: '${{ github.workspace }}/Vagrant/Ansible/MacOS/Vagrantfile'
          replacements: '$ContainerName=Ansible'

      - name: Replace string in Vagrant file
        if: runner.os == 'Linux'
        uses: datamonsters/replace-action@v2
        with:
          files: '${{ github.workspace }}/Vagrant/Ansible/Linux/Vagrantfile'
          replacements: '$ContainerName=Ansible'

#Check the runner OS to start docker and use the right VagrantFile
      - name: Start docker on macOS
        if: runner.os == 'macOS'
        run: | 
          open -a docker && sleep 10
          cd $GITHUB_WORKSPACE/Vagrant/Ansible/MacOS && vagrant up

      - name: Ensure docker daemon is running on Linux
        if: runner.os == 'Linux'
        run: |
            until [ $(systemctl is-active containerd docker) = active ]
              do
                sudo systemctl start containerd docker
                sleep 10;
              done
            cd $GITHUB_WORKSPACE/Vagrant/Ansible/Linux && vagrant up
        
