#Github Action to run the Debian-Ansible container and start Ansible to manager targets
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: Tag of the Debian-Ansible image to deploy
        type: string
        default: 'catskan/debian-ansible:3'
        required: true
      

jobs:
  start-ansible:
    name: run ansible container
    runs-on: self-hosted
    env: 
      CONTAINER_NAME: Ansible
    steps:
#Checkout the repo to have all files needed
      - name: Checkout
        uses: actions/checkout@v3

      - name: Replace tokens
        # You may pin to the exact commit or the version.
        # uses: cschleiden/replace-tokens@8e091844c27eb36853efbfade5ffca07260f0250
        uses: cschleiden/replace-tokens@v1.2
        with:
          files: '${{ github.workspace }}/Vagrant/Ansible/${{ runner.os }}/Vagrantfile'
        env:
          ContainerName: ${{ env.CONTAINER_NAME }}
          ImageTag: ${{ github.event.inputs.image_tag }}

      - name: Display VagrantFile
        run: cat '${{ github.workspace }}/Vagrant/Ansible/${{ runner.os }}/Vagrantfile'

#Check the runner OS to start docker and use the right VagrantFile
      - name: Start docker on macOS
        if: runner.os == 'macOS'
        run: | 
          open -a docker && sleep 10

      - name: Ensure docker daemon is running on Linux
        if: runner.os == 'Linux'
        run: |
            until [ "$(systemctl is-active docker)" == "active" ]
              do
                sudo systemctl start containerd docker
                sleep 10s
              done

      # - name: Check if there is an existing vagrant box with the good image
      #   run: |
      #     if [ "$(docker ps --format '{{ .Names }}')" = "${{ env.CONTAINER_NAME }}" ] && [ "$(docker ps --format '{{.Image}}')" != "${{ github.event.inputs.image_tag }}" ];
      #     then
      #       echo ok
      #       cd ${{ github.workspace }}/Vagrant/Ansible/${{ runner.os }} && vagrant destroy -f
      #     fi

      - name: Vagrant Status
        run: |
          cd ${{ github.workspace }}/Vagrant/Ansible/Linux && vagrant status

      - name: Start Vagrant box on Linux
        if: runner.os == 'Linux'
        run: |
            cd ${{ github.workspace }}/Vagrant/Ansible/Linux && sudo echo "Start vagrant box"; vagrant up

      - name: Start Vagrant box on MacOS
        if: runner.os == 'macOS'
        run: |
            cd ${{ github.workspace }}/Vagrant/Ansible/MacOS && vagrant --provision

      - name: Start ansible 
        run: |
          cd ${{ github.workspace }}/Vagrant/Ansible/MacOS && vagrant docker-exec ${{ env.CONTAINER_NAME }} -- ansible-playbook -i /share/git/resources/Ansible/Inventory/hosts.yaml /share/git/resources/Ansible/main_windows_playbook.yml
