#Github Action to run the Debian-Ansible container and start Ansible to manager targets
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: Tag of the Debian-Ansible image to deploy
        type: string
        default: 'catskan/debian-ansible:3'
        required: true
      

jobs:
  start-ansible:
    name: run ansible container
    runs-on: self-hosted
    env: 
      CONTAINER_NAME: Ansible
    steps:
#Checkout the repo to have all files needed
      - name: Checkout
        uses: actions/checkout@v3

      - name: Replace string in Vagrant file
        if: runner.os == 'macOS'
        uses: datamonsters/replace-action@v2
        with:
          files: '${{ github.workspace }}/Vagrant/Ansible/MacOS/Vagrantfile'
          replacements: | 
              $ContainerName=${{ env.CONTAINER_NAME }},
              $ImageTag=${{ inputs.image_tag }}

      - name: Replace string in Vagrant file
        if: runner.os == 'Linux'
        uses: datamonsters/replace-action@v2
        with:
          files: '${{ github.workspace }}/Vagrant/Ansible/Linux/Vagrantfile'
          replacements: | 
              $ContainerName=${{ env.CONTAINER_NAME }},
              $ImageTag=${{ inputs.image_tag }}

#Check the runner OS to start docker and use the right VagrantFile
      - name: Start docker on macOS
        if: runner.os == 'macOS'
        run: | 
          open -a docker && sleep 10

      - name: Ensure docker daemon is running on Linux
        if: runner.os == 'Linux'
        run: |
            until [ "$(systemctl is-active docker)" == "active" ]
              do
                sudo systemctl start containerd docker
                sleep 10s
              done

      - name: Check if there is an existing vagrant box with the good image
        run: |
          if [ "$(docker ps -a -q -f NAME=$CONTAINER_NAME)" ] && [ ! "$(docker ps -a -q -f ancestor=${{ github.event.inputs.python_version }})" ];
          then
            cd $GITHUB_WORKSPACE/Vagrant/Ansible/MacOS && vagrant destroy -f
          fi

      - name: Start Vagrant box on Linux
        if: runner.os == 'Linux'
        run: |
            cd $GITHUB_WORKSPACE/Vagrant/Ansible/Linux && sudo echo Start vagrant box; vagrant up

      - name: Start Vagrant box on MacOS
        if: runner.os == 'macOS'
        run: |
            cd $GITHUB_WORKSPACE/Vagrant/Ansible/MacOS && vagrant up

      - name: Start ansible 
        run: |
          cd $GITHUB_WORKSPACE/Vagrant/Ansible/MacOS && vagrant docker-exec ${{ env.CONTAINER_NAME }} -- ansible-playbook -i /share/git/resources/Ansible/Inventory/hosts.yaml /share/git/resources/Ansible/main_linux-arch_playbook.yml
