---
- name: Install Softwares
  hosts: aurelien-gaming

  tasks:
  # Install/uninstall with win_package
  - name: Download the 7-Zip package
    win_get_url:
      url: https://www.7-zip.org/a/7z2201-x64.msi
      dest: C:\temp\7z.msi

  - name: Check if 7-Zip is already installed
    win_reg_stat:
      path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{23170F69-40C1-2702-1701-000001000000}
    register: Sevenzip_installed

  - name: Ensure 7-Zip is installed via win_command
    win_command: C:\Windows\System32\msiexec.exe /i C:\temp\7z.msi /qn /norestart
    when: Sevenzip_installed.exists == false

  # Install/uninstall Firefox with win_package
  - name: Download the Firefox package
    win_get_url:
      url: https://download.mozilla.org/?product=firefox-msi-latest-ssl&os=win64&lang=en-US&_gl=1*re3fn1*_ga*MjI3NDc1NTQ0LjE2NjgyNjk0MDc.*_ga_MQ7767QQQW*MTY2ODI2OTQxNy4xLjAuMTY2ODI2OTQxNy4wLjAuMA..
      dest: C:\temp\Firefox.msi

  - name: Ensure Firefox is installed via win_command
    win_command: C:\Windows\System32\msiexec.exe /i C:\temp\Firefox.msi /passive /norestart
    #when: Sevenzip_installed.exists == false

  # Install/uninstall Firefox with win_package
  - name: Download the Nvidia package
    win_get_url:
      url: https://us.download.nvidia.com/Windows/526.86/526.86-desktop-win10-win11-64bit-international-dch-whql.exe
      dest: C:\temp\Nvidia.exe

#Install Nvidia Drivers
  - name: Ensure Firefox is installed via win_command
    win_command: C:\Windows\System32\msiexec.exe /i C:\temp\Nvidia.exe /s

