---
    - name: Get UserName SID
      win_shell: |
        (Get-WmiObject Win32_Account | Where-object -Property Name -EQ {{ user_name }}).SID
      register: raw_user_name_sid
    - set_fact:
          user_name_sid: "{{ raw_user_name_sid.stdout }}"
    - debug:
        var: user_name_sid

    - name: Create new User\Directory
      ansible.windows.win_file:
        path: E:\Aurel\Downloads
        state: directory

    - name: Change location of User\Downloads
      ansible.windows.win_regedit:
        path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders
        name: '{374DE290-123F-4565-9164-39C4925E467B}'
        data: '{{ user_directory }}\Downloads'
        type: expandstring

    - name: Change location of User\Desktop
      ansible.windows.win_regedit:
        path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders
        name: Desktop
        data: E:\Aurel\Desktop
        type: expandstring
        
    - name: Change location of User\Documents
      ansible.windows.win_regedit:
        path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders
        name: Personal
        data: E:\Aurel\Documents
        type: expandstring

    - name: Change location of User\Music
      ansible.windows.win_regedit:
        path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders
        name: My Music
        data: E:\Aurel\Music
        type: expandstring

    - name: Change location of User\Pictures
      ansible.windows.win_regedit:
        path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders
        name: My Pictures
        data: E:\Aurel\Pictures
        type: expandstring

    - name: Change location of User\Videos
      ansible.windows.win_regedit:
        path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders
        name: My Video
        data: E:\Aurel\Video
        type: expandstring

    - name: Enable Windows Explorer Libraries
      ansible.windows.win_regedit:
        path: HKCU:\Software\Classes\CLSID\{031E4825-7B94-4dc3-B131-E946B44C8DD5}
        name: System.IsPinnedToNameSpaceTree
        data: 1
        type: dword

    - name: Ensure WinRM starts when the system has settled and is ready to work reliably
      win_service:
        name: WinRM
        start_mode: delayed

    - name: Create an application shortcut for an executable in PATH to your desktop
      community.windows.win_shortcut:
        src: D:\Playnite\Playnite.DesktopApp.exe
        dest: '{{ user_directory }}\Desktop\Playnite.lnk'

    # - name: Copy AppData Directory and set it to hidden
    #   win_shell: |
    #     Copy-Item -Path "C:\Users\{{ user_name }}\AppData" -Destination "{{ user_directory }}" -Recurse -PassThru -Force ; (Get-Item {{ user_directory }}\AppData).Attributes += "Hidden"

    # - name: Create AppData Directory
    #   ansible.windows.win_file:
    #     path: E:\Aurel\AppData\Roaming
    #     state: directory
    # - name: Create Local AppData Directory
    #   ansible.windows.win_file:
    #     path: E:\Aurel\AppData\Local
    #     state: directory
    # - name: Create Local AppData Directory
    #   ansible.windows.win_file:
    #     path: E:\Aurel\AppData\Local
    #     state: directory
    # - name: Create History Directory
    #   ansible.windows.win_file:
    #     path: E:\Aurel\AppData\Local\Microsoft\Windows\History
    #     state: directory
    # - name: Create Nethood Directory
    #   ansible.windows.win_file:
    #     path: E:\Aurel\AppData\Local\Microsoft\Windows\Network Shortcuts
    #     state: directory
    # - name: Create Printhood Directory
    #   ansible.windows.win_file:
    #     path: E:\Aurel\AppData\Local\Microsoft\Windows\Printer Shortcuts
    #     state: directory
    # - name: Create StartMenu Directory
    #   ansible.windows.win_file:
    #     path: E:\Aurel\AppData\Local\Microsoft\Windows\Start Menu\Programs
    #     state: directory
    # - name: Create Startup Directory
    #   ansible.windows.win_file:
    #     path: E:\Aurel\AppData\Local\Microsoft\Windows\Start Menu\Programs\Startup
    #     state: directory
    # - name: Create Templates Directory
    #   ansible.windows.win_file:
    #     path: E:\Aurel\AppData\Local\Microsoft\Windows\Templates
    #     state: directory

      # - name: Change location of Nethood
    #   ansible.windows.win_regedit:
    #     path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders
    #     name: My Video
    #     data: E:\Aurel\AppData\Local\Microsoft\Windows\Network Shortcuts
    #     type: expandstring
    # - name: Change location of Printhood
    #   ansible.windows.win_regedit:
    #     path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders
    #     name: My Video
    #     data: E:\Aurel\AppData\Local\Microsoft\Windows\Printer Shortcuts
    #     type: expandstring
    # - name: Change location of StartMenu
    #   ansible.windows.win_regedit:
    #     path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders
    #     name: My Video
    #     data: E:\Aurel\AppData\Local\Microsoft\Windows\Start Menu\Programs
    #     type: expandstring
    # - name: Change location of Recents
    #   ansible.windows.win_regedit:
    #     path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders
    #     name: Recent
    #     data: E:\Aurel\AppData\Local\Microsoft\Windows\Recent
    #     type: expandstring
    # - name: Change location of Send To
    #   ansible.windows.win_regedit:
    #     path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders
    #     name: SendTo
    #     data: E:\Aurel\AppData\Local\Microsoft\Windows\SendTo
    #     type: expandstring
    # - name: Change location of Start Menu
    #   ansible.windows.win_regedit:
    #     path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders
    #     name: Start Menu
    #     data: E:\Aurel\AppData\Local\Microsoft\Windows\Start Menu
    #     type: expandstring
    # - name: Change location of Startup
    #   ansible.windows.win_regedit:
    #     path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders
    #     name: Startup
    #     data: E:\Aurel\AppData\Local\Microsoft\Windows\Start Menu\Programs\Startup
    #     type: expandstring
    # - name: Change location of Templates
    #   ansible.windows.win_regedit:
    #     path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders
    #     name: Templates
    #     data: E:\Aurel\AppData\Local\Microsoft\Windows\Templates
    #     type: expandstring

      # - name: Change location of User\AppData
    #   ansible.windows.win_regedit:
    #     path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders
    #     name: AppData
    #     data: E:\Aurel\AppData\Roaming
    #     type: expandstring
    # - name: Change location of User\Local AppData
    #   ansible.windows.win_regedit:
    #     path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders
    #     name: Local AppData
    #     data: E:\Aurel\AppData\Local
    #     type: expandstring
    # - name: Change location of User\History
    #   ansible.windows.win_regedit:
    #     path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders
    #     name: Local AppData
    #     data: E:\Aurel\AppData\Local\Microsoft\Windows\History
    #     type: expandstring