---
##########################################Change hostname##########################################
    - name: Change the hostname to sample-hostname
      ansible.windows.win_hostname:
        name: aurelien-gaming
      register: restart

    - name: Reboot
      ansible.windows.win_reboot:
      when: restart.reboot_required

  ##########################################Change power plan##########################################
    - name: Change power plan to high performance
      community.windows.win_power_plan:
        name: high performance

  ##########################################Set auto logon##########################################
    - name: Set autologon for Aurel
      community.windows.win_auto_logon:
        username: Aurel
        password: '{{ user_name_password}}'

  # ##########################################Mount WebDAV##########################################
  #   - name: Create mapped drive with credentials and save the username and password
  #     block:
  #     - name: Save the network credentials required for the mapped drive
  #       win_credential:
  #         name: nas.mapn.fr
  #         type: domain_password
  #         username: '{{ webdav_username }}'
  #         secret: '{{ webdav_password }}'
  #         state: present

  #     - name: Create a mapped drive that requires authentication
  #       win_mapped_drive:
  #         letter: N
  #         path: \\nas.mapn.fr@SSL\Aurelien
  #         state: present
  #     vars:
  #       # become is required to save and retrieve the credentials in the tasks
  #       ansible_become: yes
  #       ansible_become_method: runas
  #       ansible_become_user: '{{ ansible_user }}'
  #       ansible_become_pass: '{{ ansible_password }}'



  ##########################################Install all Windows Updates##########################################
    - name: Install all updates and reboot as many times as needed
      ansible.windows.win_updates:
        category_names: '*'
        reboot: yes
        reboot_timeout: 3600




